CREATE DATABASE company_case_study_db;

USE company_case_study_db;

CREATE TABLE DEPARTMENT (
    DNUM              INT IDENTITY(1,1) PRIMARY KEY,
    DName             VARCHAR(100) NOT NULL,
    Manager_SSN       VARCHAR(20),
    Manager_Hire_Date DATE NOT NULL,
    UNIQUE (Manager_SSN)
);

CREATE TABLE EMPLOYEE (
    SSN            VARCHAR(20) PRIMARY KEY,
    Fname          VARCHAR(100) NOT NULL,
    Lname          VARCHAR(100) NOT NULL,
    Birth_Date     DATE NOT NULL,
    Gender         VARCHAR(20),
    DNUM           INT NOT NULL,
    Supervisor_SSN VARCHAR(20),
    FOREIGN KEY (DNUM) REFERENCES DEPARTMENT(DNUM),
    FOREIGN KEY (Supervisor_SSN) REFERENCES EMPLOYEE(SSN)
);

ALTER TABLE DEPARTMENT
ADD CONSTRAINT FK_Department_Manager
FOREIGN KEY (Manager_SSN) REFERENCES EMPLOYEE(SSN);

ALTER TABLE DEPARTMENT
ALTER COLUMN Manager_SSN VARCHAR(20) NOT NULL;

CREATE TABLE DEPARTMENT_LOCATIONS (
    DNUM     INT NOT NULL,
    Location VARCHAR(150) NOT NULL,
    PRIMARY KEY (DNUM, Location),
    FOREIGN KEY (DNUM) REFERENCES DEPARTMENT(DNUM)
);

CREATE TABLE PROJECT (
    PNumber  INT PRIMARY KEY,
    Pname    VARCHAR(150) NOT NULL,
    Location VARCHAR(150),
    City     VARCHAR(100),
    DNUM     INT NOT NULL,
    FOREIGN KEY (DNUM) REFERENCES DEPARTMENT(DNUM)
);

CREATE TABLE WORKS_ON (
    SSN     VARCHAR(20) NOT NULL,
    PNumber INT NOT NULL,
    Hours   DECIMAL(6,2) NOT NULL,
    PRIMARY KEY (SSN, PNumber),
    FOREIGN KEY (SSN) REFERENCES EMPLOYEE(SSN),
    FOREIGN KEY (PNumber) REFERENCES PROJECT(PNumber),
    CHECK (Hours >= 0)
);

CREATE TABLE DEPENDENT (
    Employee_SSN   VARCHAR(20) NOT NULL,
    Dependent_Name VARCHAR(150) NOT NULL,
    Gender         VARCHAR(20),
    Birth_Date     DATE,
    PRIMARY KEY (Employee_SSN, Dependent_Name),
    FOREIGN KEY (Employee_SSN) REFERENCES EMPLOYEE(SSN)
    ON DELETE CASCADE
);

SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME;
